source "https://rubygems.org"

ruby "2.2.1"

gem "rails", "4.2.3"
gem "pg"
gem "sass-rails", "~> 5.0"
gem "bootstrap-sass", "~> 3.3.5"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "turbolinks"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "bower-rails", "~> 0.10.0"
gem "unicorn"
gem "capistrano-rails", group: :development
gem "devise"
gem "cancancan", "~> 1.10"
gem "apartment"
gem "figaro"
gem "globalize", "~> 5.0.0"
gem "globalize-accessors"
gem "nprogress-rails"
gem "react-rails", "~> 1.0"
gem "i18n-js"
gem "carrierwave"
gem "mini_magick"
gem "money-rails"
gem "country_select"
gem "config"
gem "actionpack-action_caching"
gem "kaminari"

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "rspec-rails", "~> 3.0"
  gem "rspec-collection_matchers"
  gem "shoulda-matchers"
  gem "shoulda-callback-matchers", "~> 1.1.1"
  gem "factory_girl_rails"
  gem "faker"
  gem "capybara"
  gem "database_cleaner"
  gem "launchy"
  gem "selenium-webdriver"
end
