default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shopstory_dev

staging:
  <<: *default
  database: shopstory_staging

production:
  <<: *default
  database: shopstory-production

