app:
  domains: ["shopstory.dev"]
  domain: shopstory.dev
  root_subdomains: ["www"]
shop:
  default_name: ShopStory
  default_currency: KRW
  default_country: KR
  default_timezone: Asia/Seoul
paging:
  order: 20
