app:
  domains: ["shopstory.local"]
  domain: shopstory.local
  root_subdomains: ["www"]
shop:
  default_name: ShopStory
  default_currency: USD
  default_country: US
  default_timezone: America/New_York
paging:
  order: 20
queues:
  default: default-development
