app:
  domains: ["shopstory.xyz"]
  domain: shopstory.xyz
  root_subdomains: ["www"]
shop:
  default_name: ShopStory
  default_currency: USD
  default_country: US
  default_timezone: America/New_York
tester:
  name: shopstory
  password: n3vermind
paging:
  order: 20
