app:
  domains: ["singularcart.com"]
  domain: singularcart.com
  root_subdomains: ["www"]
shop:
  default_name: Singular Cart
  default_currency: USD
  default_country: US
  default_timezone: America/New_York
tester:
  name: shopstory
  password: n3vermind
paging:
  order: 20
queues:
  default: default
