app:
  domains: ["singularcart-staging.com"]
  domain: singularcart.com
  root_subdomains: ["www"]
shop:
  default_name: Singular Cart
  default_currency: KRW
  default_country: KR
  default_timezone: Asia/Seoul
tester:
  name: shopstory_staging
  password: n3vermind
paging:
  order: 20
queues:
  default: default-staging
