app:
  domains: ["shopstory.co.kr", "shopstoryapp.com"]
  domain: shopstory.co.kr
  root_subdomains: ["www"]
shop:
  default_name: ShopStory
  default_currency: KRW
  default_country: KR
  default_timezone: Asia/Seoul
tester:
  name: shopstory_staging
  password: n3vermind
paging:
  order: 20
