app:
  domains: ["singularcart.com"]
  domain: singularcart.com
  root_subdomains: ["www"]
shop:
  default_name: Singular Cart
  default_currency: KRW
  default_country: KR
  default_timezone: Asia/Seoul
paging:
  order: 20
