app:
  domains: ["shopstory.co.kr", "shopstory.com"]
  domain: shopstory.com
  root_subdomains: ["www"]
shop:
  default_name: ShopStory
  default_currency: KRW
  default_country: KR
  default_timezone: Asia/Seoul
paging:
  order: 20
